abbreviations:
  SS: STAINLESS STEEL
  CS: CARBON STEEL
  AS: ALLOY STEEL
  GI: GALVANIZED IRON
  MS: MILD STEEL
  GR: GRADE
  HEX: HEXAGON
  HD: HEAD
  BRG: BEARING
  VLV: VALVE
  GSKT: GASKET
  CBL: CABLE
  NB: NOMINAL BORE
  DN: DIAMETER NOMINAL
  SCH: SCHEDULE
  THK: THICKNESS
  OD: OUTSIDE DIAMETER
  ID: INSIDE DIAMETER
  PN: PRESSURE NOMINAL
  CLASS: CLASS
  CL: CLASS
  PSI: PSI
